databases:
  - name: shoplify
    databaseName: shoplify
    user: shoplify

services:
  - type: web
    name: shoplify
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoplify
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
